# -*- coding: utf-8 -*-
"""tech_challenge_nps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0FwFWnnIYVQvMCgB0e83gUph9iV82kX

# Tech Challenge - Fase 1
## Análise de NPS em E-commerce

### Objetivo
Este notebook apresenta a análise exploratória de uma base de dados de clientes de um e-commerce, com o objetivo de identificar os fatores que influenciam a satisfação dos consumidores, medida pelo Net Promoter Score (NPS). Além da EDA, é proposta uma solução baseada em Machine Learning para prever a satisfação dos clientes antes da aplicação da pesquisa de NPS.

## **1. Importação das bibliotecas**
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

"""## **2. Carregamento da base de dados**"""

df = pd.read_csv('/content/desafio_nps_fase_1.csv')

"""## **3. Conhecendo a base de dados**
Nesta etapa são apresentadas as principais características da base de dados, incluindo sua estrutura, tipos de variáveis e estatísticas descritivas.
"""

df.shape

df.columns

df.info()

df.describe()

"""## **4. Qualidade dos dados**
Nesta etapa é verificada a existência de valores ausentes na base de dados.
"""

df.isnull().sum()

"""### **Resultado:** Não foram encontrados valores nulos na base de dados, indicando boa qualidade inicial para as análises.

## **5. Distribuição do NPS**
Nesta etapa, os clientes são classificados em detratores, neutros e promotores, conforme a metodologia do Net Promoter Score (NPS). Em seguida, é analisada a distribuição dessas categorias na base de dados.
"""

def classificar_nps(nota):
    if nota <= 6:
        return 'Detrator'
    elif nota <= 8:
        return 'Neutro'
    else:
        return 'Promotor'

df['nps_categoria'] = df['nps_score'].apply(classificar_nps)

df['nps_categoria'].value_counts()

round(df['nps_categoria'].value_counts(normalize=True) * 100, 2)

df['nps_categoria'].value_counts().plot(kind='bar')

plt.title('Distribuição das Categorias de NPS')
plt.xlabel('Categoria')
plt.ylabel('Quantidade')

plt.show()

plt.figure(figsize=(10,5))

df['nps_score'].hist(bins=11)

plt.title('Distribuição das Notas de NPS')
plt.xlabel('Nota')
plt.ylabel('Quantidade de Clientes')

plt.show()

"""## **6. Análise Exploratória dos Dados (EDA)**

### **6.1 Impacto da Logística**
Nesta etapa são analisados os indicadores logísticos para verificar sua relação com a satisfação dos clientes.
"""

df.groupby('nps_categoria')['delivery_delay_days'].mean()

df.groupby('nps_categoria')['delivery_time_days'].mean()

df.groupby('nps_categoria')['delivery_delay_days'].mean().plot(kind='bar')

plt.title('Atraso Médio por Categoria de NPS')
plt.xlabel('Categoria')
plt.ylabel('Dias de Atraso')

plt.show()

"""### **6.2 Atendimento ao Cliente**
Nesta etapa são analisados indicadores relacionados ao atendimento ao cliente.
"""

df.groupby('nps_categoria')['customer_service_contacts'].mean()

df.groupby('nps_categoria')['complaints_count'].mean()

df.groupby('nps_categoria')['resolution_time_days'].mean()

df.groupby('nps_categoria')['csat_internal_score'].mean()

df.groupby('nps_categoria')['complaints_count'].mean().plot(kind='bar')

plt.title('Reclamações Médias por Categoria de NPS')
plt.xlabel('Categoria')
plt.ylabel('Número Médio de Reclamações')

plt.show()

"""### **6.3 Correlação entre Variáveis**
Foi calculada a correlação entre as variáveis numéricas e o NPS para identificar quais apresentam maior associação linear com a satisfação do cliente.
"""

correlacoes = df.corr(numeric_only=True)['nps_score'].sort_values()
correlacoes

"""### **6.4 Diferenças por Região**"""

df.groupby('customer_region')['nps_score'].mean().sort_values()

"""### **6.5 Recompra e Fidelização**"""

df.groupby('repeat_purchase_30d')['nps_score'].mean()

nps_recompra = df.groupby('repeat_purchase_30d')['nps_score'].mean()

plt.figure(figsize=(6,4))
nps_recompra.plot(kind='bar')

plt.title('NPS Médio por Recompra em 30 Dias')
plt.xlabel('Recompra em 30 dias')
plt.ylabel('NPS Médio')

plt.xticks([0,1], ['Não', 'Sim'], rotation=0)

plt.show()

"""### **6.6 Ponto de Ruptura da Experiência**"""

df.groupby('delivery_delay_days')['nps_score'].mean()

df.groupby('delivery_delay_days')['nps_score'].mean().plot(marker='o')

plt.title('NPS Médio por Dias de Atraso')
plt.xlabel('Dias de Atraso')
plt.ylabel('NPS Médio')

plt.grid(True)

plt.show()

"""## **7. Modelo Preditivo**
Como complemento à análise exploratória, foi desenvolvido um modelo de classificação utilizando Random Forest para prever a categoria de satisfação dos clientes.

### **7.1 Definição da variável alvo e das variáveis de entrada**
"""

features = [
    'delivery_delay_days',
    'complaints_count',
    'customer_service_contacts',
    'resolution_time_days',
    'delivery_time_days',
    'order_value',
    'items_quantity',
    'customer_tenure_months',
    'customer_age'
]

X = df[features]
y = df['nps_categoria']

"""### **7.2 Separação treino/teste**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""### **7.3 Treinamento**"""

modelo = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

modelo.fit(X_train, y_train)

"""### **7.4 Predição**"""

y_pred = modelo.predict(X_test)

"""### **7.5 Avaliação**"""

print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred)

ConfusionMatrixDisplay.from_estimator(
    modelo,
    X_test,
    y_test
)

plt.show()

"""### **7.6 Importância das Variáveis**"""

importancias = pd.Series(
    modelo.feature_importances_,
    index=features
).sort_values(ascending=False)

print(importancias)

importancias.plot(kind='bar')

plt.title('Importância das Variáveis na Previsão do NPS')
plt.ylabel('Importância')

plt.show()